version: "3"
services:
  la-boite:
    build: packages/la-boite
    volumes:
        - ./packages/la-boite:/app
    ports:
            - 3001:3001
    environment:
        - NODE_ENV=development
  example-app:
    build: packages/example-app
    volumes:
      - ./packages/example-app:/app
    ports:
        - 3000:3000
    environment:
        - NODE_ENV=development