version: "3"
services:

  la-boite:
    build: packages/la-boite
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - GIT_EN_BOITE_PG_URL=postgres://postgres:postgres@localhost:5432/git-en-boite-development
      - REDIS_URL=redis://redis:6379

  pg:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - $HOME/.docker-volumes/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    ports:
      - 6379:6379
