version: "3"
services:
  web-server:
    build: .
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - GIT_ROOT=/git-repos
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/git-en-boite-development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - git-worker
    command: yarn app start:server
    volumes:
      - ./git-repos:/git-repos

  git-worker:
    build: .
    environment:
      - NODE_ENV=development
      - GIT_ROOT=/git-repos
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/git-en-boite-development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    command: yarn app start:worker
    volumes:
      - ./git-repos:/git-repos

  smoke-tests:
    build: .
    environment:
      - smoke_tests_web_server_url=http://web-server:3001
      - smoke_tests_remote_repo_url
    command: "echo \"NO OP: please run `yarn smoke start`\""

  postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=git-en-boite-development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
