version: "3"
services:
  app:
    build: packages/la-boite
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/git-en-boite-development
      - REDIS_URL=redis://redis:6379
    links:
      - postgres
      - redis

  postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=git-en-boite-development
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:latest
