name: Test and publish container

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test all packages
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GIT_ROOT: /git-repos
      REDIS_URL: redis://localhost:6379
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: egordm/gha-yarn-node-cache@v1
      - uses: supercharge/redis-github-action@1.1.0
      - name: Install dependencies
        run: yarn install
      - name: Build Typescript
        run: yarn build
      - name: Run tests in each workspace
        run: yarn test
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#cucumber-gherkin-editor"
        if: failure()

  publish-docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.run_number }}#${GITHUB_SHA::8}" > .build-number
      - run: docker build -t smartbear/git-en-boite:latest .
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - run: docker tag smartbear/git-en-boite:latest smartbear/git-en-boite:${{ github.sha }}
      - run: docker push smartbear/git-en-boite:${{ github.sha }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#cucumber-gherkin-editor"
        if: always()

  test-docker-image:
    name: "Smoke tests: locally-running published docker image"
    runs-on: ubuntu-latest
    needs: [publish-docker-image]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      smoke_tests_web_server_url: http://git-en-boite:3001
      smoke_tests_remote_repo_url: ${{ secrets.SMOKE_TESTS_CI_REMOTE_REPO_URL }}
      GIT_EN_BOITE_IMAGE_VERSION: ${{ github.sha }}
      COMPOSE_FILE: docker-compose-smoke-test.yml
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose config
      - run: docker-compose up --no-build --detach
      - run: docker-compose logs
      - uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:3001
          timeout: 60000
          verbose: true
      - run: docker-compose run git-en-boite yarn smoke start
      - run: docker-compose stop
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#cucumber-gherkin-editor"
        if: failure()
