name: Test and publish container

on:
  push:
    branches: [main, ci, publish-after-running-smoke-test]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test all packages
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GIT_ROOT: /git-repos
      REDIS_URL: redis://localhost:6379
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: egordm/gha-yarn-node-cache@v1
      - uses: supercharge/redis-github-action@1.1.0
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Run tests in each workspace
        run: yarn test
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#cucumber-gherkin-editor"
        if: failure()

  publish-docker-image:
    name: Build & publish Docker image
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      smoke_tests_web_server_url: http://git-en-boite:3001
      smoke_tests_remote_repo_url: ${{ secrets.SMOKE_TESTS_CI_REMOTE_REPO_URL }}
      GIT_EN_BOITE_IMAGE_VERSION: ${{ github.sha }}
      COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    steps:
      - uses: actions/checkout@v2
      - name: BUILD -- Generate .build-number
        run: echo "${{ github.run_number }}#${{ github.sha }}" > .build-number
      - name: BUILD -- Build smartbear/git-en-boite docker image
        run: docker build -t smartbear/git-en-boite:latest -t smartbear/git-en-boite:${{ github.sha }} .
      - name: BUILD -- Set up qemu
        uses: docker/setup-qemu-action@v1
      - name: BUILD -- Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: SMOKE TESTS -- Start services
        run: docker-compose up --no-build --detach
      - name: SMOKE TESTS -- Services start logs
        run: docker-compose logs
      - name: SMOKE TESTS -- Wait for services to be ready
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:3001
          timeout: 60000
          verbose: true
      - name: SMOKE TESTS -- Run smoke tests
        run: docker-compose run smoke-tests yarn smoke start
      - name: PUBLISH -- Authenticate with DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}
      - name: PUBLISH -- Push smartbear/git-en-boite
        run: docker push smartbear/git-en-boite
      - name: "REPORT -- Notify #cucumber-gherkin-editor channel"
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#cucumber-gherkin-editor"
        if: always()
