name: Run tests

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main]

jobs:
  test-core:
    name: Run tests on core package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: egordm/gha-yarn-node-cache@v1
      - run: yarn install
      - run: yarn core test

  test-local-git:
    name: Run tests on local-git package
    runs-on: ubuntu-latest
    env:
      GIT_ROOT: /git-repos
      REDIS_URL: redis://localhost:6379
    steps:
      - uses: actions/checkout@v2
      - uses: supercharge/redis-github-action@1.1.0
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: egordm/gha-yarn-node-cache@v1
      - run: yarn install
      - run: yarn local-git test

  test-app:
    name: Run tests on app package
    runs-on: ubuntu-latest
    env:
      GIT_ROOT: /git-repos
      REDIS_URL: redis://localhost:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: egordm/gha-yarn-node-cache@v1
      - run: yarn install
      - run: yarn app test

  test-web:
    name: Run tests on web package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: egordm/gha-yarn-node-cache@v1
      - run: yarn install
      - run: yarn web test

  publish-image:
    name: Build and publish Docker image to smartbear/git-en-boite<git-sha>
    runs-on: ubuntu-latest
    needs: [test-core, test-local-git, test-app, test-web]
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            smartbear/git-en-boite:${{ github.sha }}
            smartbear/git-en-boite:latest
